version: "3.8"


services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpswd
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data